[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.build]
cmds = [
    'chmod +x ./mvnw',
    './mvnw clean package -DskipTests -Pproduction'
]

[start]
cmd = 'java -jar target/task-management-system-0.0.1-SNAPSHOT.jar'

[variables]
MAVEN_OPTS = '-Xmx512m'
SPRING_PROFILES_ACTIVE = 'prod'
JAVA_VERSION = '17'
