[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.build]
cmds = [
    'chmod +x ./mvnw',
    './mvnw clean package -DskipTests -Pproduction'
]

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod $JAVA_OPTS -jar target/*.jar'

[variables]
MAVEN_OPTS = '-Xmx1024m'
SPRING_PROFILES_ACTIVE = 'prod'
