services:
  - type: web
    name: task-management-system
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    plan: free
  - type: pserv
    name: task-management-postgres
    env: docker
    plan: free